<?php 
require(ROUTE_DIR.'lib/session.php');
require(ROUTE_DIR.'lib/validator.php');
require(ROUTE_DIR.'lib/upload.php');
require(ROUTE_DIR.'lib/database.php');
require(ROUTE_DIR.'lib/autorisation.php');
require(ROUTE_DIR.'models/proprietaire.model.php');
require(ROUTE_DIR.'models/client.model.php');
require(ROUTE_DIR.'models/gestionnaire.model.php');
require(ROUTE_DIR.'models/utilisateurs.model.php');
?>